### ISSUE TITLE
less 中的嵌套还能用吗？

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/less-2-css#1]

**Comment by yuaanlin** [comment]
@xiaohuoni 可以的，嵌套语法由 postcss 进行处理 👍

**Comment by xiaohuoni** [comment]
后续修改 css 编写的时候，是一样的写法吗？有其他注意事项吗？

**Comment by yuaanlin** [comment]
@xiaohuoni 后续对于 `.css` 文件只能用普通的 CSS 语法或 PostCSS 插件支持的语法，不能用 LESS 语法（除非把文件名改回 `.less`）

**Comment by xiaohuoni** [comment]
现在项目交付中，很不想用 less 了，但是几乎都会（仅用到）用到 less 中的嵌套。
很愁，干掉 less 直接提速。

**Comment by yuaanlin** [comment]
@xiaohuoni 那这个工具很适合你，他可以帮你把几乎所有的样式文件改成 `.css` 文件 👍

**Comment by xiaohuoni** [comment]
PostCSS 插件支持的语法，支持嵌套？

**Comment by yuaanlin** [comment]
@xiaohuoni https://github.com/postcss/postcss-nested#readme

**Comment by xiaohuoni** [comment]
霖哥就是强👍
